/// @description Insert description here
 // You can write your code in this editor
 #region enemy
 draw_sprite_general(sprite,0,
 	arrowLEFT[now,0],
 	arrowLEFT[now,1],
 	arrowLEFT[now,2],
 	arrowLEFT[now,3],xe,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowDOWN[now,0],
 	arrowDOWN[now,1],
 	arrowDOWN[now,2],
 	arrowDOWN[now,3],xe+xoffset,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowUP[now,0],
 	arrowUP[now,1],
 	arrowUP[now,2],
 	arrowUP[now,3],xe+xoffset*2,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowRIGHT[now,0],
 	arrowRIGHT[now,1],
 	arrowRIGHT[now,2],
 	arrowRIGHT[now,3],xe+xoffset*3,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 #endregion
 draw_sprite_general(sprite,0,
 	arrowLEFT[now,0],
 	arrowLEFT[now,1],
 	arrowLEFT[now,2],
 	arrowLEFT[now,3],xp,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowDOWN[now,0],
 	arrowDOWN[now,1],
 	arrowDOWN[now,2],
 	arrowDOWN[now,3],xp+xoffset,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowUP[now,0],
 	arrowUP[now,1],
 	arrowUP[now,2],
 	arrowUP[now,3],xp+xoffset*2,y,.75,.75,0,c_white,c_white,c_white,c_white,1);
 draw_sprite_general(sprite,0,
 	arrowRIGHT[now,0],
 	arrowRIGHT[now,1],
 	arrowRIGHT[now,2],
 	arrowRIGHT[now,3],xp+xoffset*3,y,.75,.75,0,c_white,c_white,c_white,c_white,1);